language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
sudo: false
addons:
  firefox: "34.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
notifications:
  email:
    on_success: never
